### ISSUE TITLE
Boostrappable?

### ISSUE THREAD

**Issue by matlink** [bogdan-kulynych/libshe#2]
Do you think this scheme can be one day bootstrappable?

Nice work by the way ;)

**Comment by bogdan-kulynych** [comment]
Hey @matlink, thanks for commenting.

The original DGHV scheme is bootstrappable, but I didn't investigate whether this modification is bootstrappable as well, my gut feel it isn't because a lot of insides of DGHV were cut out. In the nearest months, I intend to work on creating a different backend based on NTRU, keeping API similar to the current one. That version will hopefully be bootstrappable.
